### ISSUE TITLE
Support "Pwned Passwords" API v2 Endpoint

### ISSUE THREAD

**Issue by cmlh** [cmlh/Maltego-haveibeenpwned#15]
Support [`Pwned Passwords` API v2 endpoint](https://haveibeenpwned.com/API/v2#PwnedPasswords).

References
- https://www.troyhunt.com/introducing-306-million-freely-downloadable-pwned-passwords/
- https://haveibeenpwned.com/Passwords

**Implementation**
- [X] maltego.Hash
- [x] haveibeenpwned.Password

**Comment by cmlh** [comment]
**Integration Pattern**

Transforms
- From `haveibeenpwned.Password` to `maltego.Hash` SHA-1
- From `maltego.Hash` SHA-1 to `haveibeenpwned.linkAnalysis`
- From `haveibeenpwned.Password` to `haveibeenpwned.linkAnalysis`

Custom Entities
- `haveibeenpwned.Password`
- `haveibeenpwned.linkAnalysis` returns [password] "_Found_" (for `HTTP Status 200`) or [password] "_Not Found_" (for `HTTP Status 400`)

Entity Input Value
- [test](https://haveibeenpwned.com/API/v2#PwnedPasswords) for `haveibeenpwned.Password`
- [5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8](https://haveibeenpwned.com/API/v2#PwnedPasswords) for `maltego.Hash` SHA-1
- [p@55w0rd](https://www.troyhunt.com/introducing-306-million-freely-downloadable-pwned-passwords/) for `haveibeenpwned.Password`
- [ce0b2b771f7d468c0141918daea704e0e5ad45db](https://www.troyhunt.com/introducing-306-million-freely-downloadable-pwned-passwords/) for `haveibeenpwned.Password`
- [ce0b2b771f7d468c0141918daea704e0e5ad45db](https://www.troyhunt.com/introducing-306-million-freely-downloadable-pwned-passwords/) for `maltego-Hash` SHA-1

**Comment by SudhanshuC** [comment]
For the machine, it can take 'haveibeenpwned.Password' as input and give out 'haveibeenpwned.linkAnalysis' and 'maltego.Hash' as first level of output. Then 'maltego.Hash' can be further used as input to get 'haveibeenpwned.linkAnalysis'. In most of the cases it will generate same result but there might be instances where only either one of them will.

**Comment by cmlh** [comment]
@SudhanshuC 

Yes, the input value [ce0b2b771f7d468c0141918daea704e0e5ad45db](https://www.troyhunt.com/introducing-306-million-freely-downloadable-pwned-passwords/) of  `haveibeenpwned.Password` would also return a `maltego-Hash` SHA-1 entity of  [ce0b2b771f7d468c0141918daea704e0e5ad45db](https://www.troyhunt.com/introducing-306-million-freely-downloadable-pwned-passwords/) too with the `?originalPasswordIsAHash=true` parameter which would link to the initial 'haveibeenpwned.Password` entity.

I have amended the [Maltego] Machine specified above.

**Comment by cmlh** [comment]
**Implementation**
- [X] maltego.Hash
- [ ] haveibeenpwned.Password

**Comment by cmlh** [comment]
Fix https://github.com/cmlh/Maltego-haveibeenpwned/commit/54951e5fa655e484b7673c5bead997f0bff95cdb
