### ISSUE TITLE
Maltego Err 

### ISSUE THREAD

**Issue by timonitor** [cmlh/Maltego-haveibeenpwned#26]
When i launch the HIBP transform i get the error "responded with an HTTP 503, we wanted a 200!" is there a way to remove the popup form showing up and blocking my research?

**Comment by cmlh** [comment]
@timonitor 

Apologies for the delay but I have just seen issue #26.

What was the Input Entity and associated Transform causing the error?

**Comment by cmlh** [comment]
@timonitor 

I will close this issue, please reopen this if #26 occurs again.
